### ISSUE TITLE
Documentation is not explicit on what the exact name of the Ansible Host file should be

### ISSUE THREAD

**Issue by GiorgioRegni** [GiorgioRegni/AnsibleScratch#11]
Should it be hosts? or ansible_hosts or something else?

**Comment by ratmav** [comment]
It should be `ansible_hosts`, but it can be modifiable per the [Ansible documentation](http://docs.ansible.com/ansible/intro_inventory.html). I'll update the README under the [Ansible Hosts](https://github.com/GiorgioRegni/AnsibleScratch#ansible-hosts) heading to state that explicitly.

**Comment by ratmav** [comment]
README updated.

**Comment by GiorgioRegni** [comment]
Thanks
